---
language: ruby
os: linux
dist: bionic
rvm:
  - 2.7.0
env:
  global:
    - CC_TEST_REPORTER_ID=1ff295d688443aabf482bcb9980bf551e23a83f8edc96cb0dbc0d3ec6e22bcdd
before_install:
  - gem install bundler:2.1.4
  - bundle config set without 'development production'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only: master
notifications:
  email: false
