---
language: ruby
os: linux
dist: bionic
cache: bundler
before_install:
  - gem install bundler:2.1.2
  - bundle config set without 'development production'
script: bundle exec rspec
rvm:
  - 2.7.0
branches:
  only: master
notifications:
  email: false
