---
language: ruby
dist: bionic
cache: bundler
before_install: gem install bundler
install: bundle install --without development production
script: bundle exec rspec
rvm:
  - 2.7.0
branches:
  only: master
notifications:
  email: false
